# Generated by Django 4.2.17 on 2025-01-04 22:50

# Django imports
from django.db import migrations, models

# external imports
import django_simple_file_handler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "generated_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "extra_text",
                    models.TextField(blank=True, verbose_name="extra text (optional)"),
                ),
                (
                    "saved_file",
                    models.FileField(
                        max_length=255,
                        upload_to=django_simple_file_handler.models.create_file_path,
                        verbose_name="uploaded file",
                    ),
                ),
                ("title", models.CharField(max_length=245, unique=True)),
                ("version", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ra", "Risk Assessment"),
                            ("sop", "Standard Operator Procedure"),
                            ("manual", "Manual/Instructions"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "document (categorized)",
                "verbose_name_plural": "documents (categorized)",
            },
        ),
    ]
