# Generated by Django 4.2.17 on 2025-01-07 15:35

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labman_utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="version",
            field=models.FloatField(default=0),
        ),
    ]
