# Generated by Django 4.2.17 on 2025-01-23 17:30

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labman_utils", "0002_alter_document_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="review_date",
            field=models.DateField(blank=True, help_text="Date document should be reviewed on.", null=True),
        ),
    ]
