# Generated by Django 4.2.17 on 2025-01-28 22:01

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labman_utils", "0003_document_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("ra", "Risk Assessment"),
                    ("sop", "Standard Operator Procedure"),
                    ("coshh", "COSHH Forms"),
                    ("manual", "Manual/Instructions"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
