# Generated by Django 4.2.18 on 2025-02-04 17:11

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labman_utils", "0005_groupedtree_groupedtreeitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupedtreeitem",
            name="tree",
            field=models.ForeignKey(
                help_text="Site tree this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_tree",
                to="labman_utils.groupedtree",
                verbose_name="Site Tree",
            ),
        ),
    ]
