# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', tinymce.models.HTMLField(default=b'&nbsp;')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm_utils', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='UserList_level',
            fields=[
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', tinymce.models.HTMLField(default=b'&nbsp;')),
                ('level', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'user level label',
            },
        ),
        migrations.AddField(
            model_name='userlist',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lm_utils.UserList_level'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOf', to=settings.AUTH_USER_MODEL),
        ),
    ]
