# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 18:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lm_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylabels',
            name='description',
            field=tinymce.models.HTMLField(default='&nbsp;'),
        ),
    ]
