# Generated by Django 4.2.2 on 2023-06-24 17:08

# Django imports
from django.db import migrations, models

# external imports
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_pages_account_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("name", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("level", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
    ]
