# Generated by Django 4.2.18 on 2025-02-04 17:11

# Django imports
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0013_alter_watermark_image"),
        ("accounts", "0003_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="photos",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="accounts",
                to="photologue.photo",
            ),
        ),
    ]
