# Generated by Django 4.2.2 on 2023-06-25 17:35

# Django imports
from django.db import migrations, models

# external imports
import sortedm2m.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("short_name", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=20)),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="project",
        ),
        migrations.AddField(
            model_name="account",
            name="project",
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to="accounts.project"),
        ),
    ]
