# Generated by Django 4.2.19 on 2025-02-19 15:59

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="project",
        ),
    ]
