# Generated by Django 4.2.2 on 2023-06-25 19:36

# Django imports
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0012_alter_photo_effect"),
        ("flatpages", "0001_initial"),
        ("accounts", "0004_project_remove_account_project_account_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="pages",
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to="flatpages.flatpage"),
        ),
        migrations.AlterField(
            model_name="account",
            name="photos",
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to="photologue.photo"),
        ),
        migrations.AlterField(
            model_name="account",
            name="project",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, related_name="researchers", to="accounts.project"
            ),
        ),
    ]
