# Generated by Django 4.2.3 on 2023-07-17 15:25

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_pages_alter_account_photos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [("access_admin", "Can Access the Admin backend")],
            },
        ),
    ]
