# Generated by Django 4.2.19 on 2025-02-19 20:20

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_account_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
