# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:22
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lm_utils.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', tinymce.models.HTMLField(default=b'&nbsp;')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='locations.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owned_Equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'equipment',
            },
            bases=(models.Model, lm_utils.models.HasUsers),
        ),
        migrations.CreateModel(
            name='Equipment_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', tinymce.models.HTMLField(default=b'&nbsp;')),
                ('status', colorful.fields.RGBColorField()),
            ],
            options={
                'verbose_name': 'equipment status label',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment_Status'),
        ),
    ]
