# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=tinymce.models.HTMLField(default='&nbsp;'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment_status',
            name='description',
            field=tinymce.models.HTMLField(default='&nbsp;'),
        ),
    ]
