# Generated by Django 4.2.2 on 2023-06-18 20:29

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# external imports
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photologue", "0012_alter_photo_effect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("name",), name="Unique Location Name"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to="equipment.location"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="photos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="equipment", to="photologue.photo"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(fields=("name",), name="Unique Equipment Name"),
        ),
    ]
