# Generated by Django 4.2.2 on 2023-06-18 20:56

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment Item", "verbose_name_plural": "Equipment Items"},
        ),
        migrations.AddField(
            model_name="location",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_locations",
                to="equipment.location",
            ),
        ),
    ]
