# Generated by Django 4.2.17 on 2025-01-10 13:41

# Django imports
from django.db import migrations

# external imports
import labman_utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_equipment_category_equipment_offline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=labman_utils.models.ObfuscatedHTMLField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=labman_utils.models.ObfuscatedHTMLField(),
        ),
        migrations.AlterField(
            model_name="shift",
            name="description",
            field=labman_utils.models.ObfuscatedHTMLField(),
        ),
    ]
