# Generated by Django 4.2.2 on 2023-06-18 22:02

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0012_alter_photo_effect"),
        ("equipment", "0002_alter_equipment_options_location_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="photos",
        ),
        migrations.AddField(
            model_name="equipment",
            name="photos",
            field=models.ManyToManyField(related_name="equipment", to="photologue.photo"),
        ),
    ]
