# Generated by Django 4.2.17 on 2025-01-17 21:24

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_equipment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsignoff",
            name="version",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cryostat", "Cryostat"),
                    ("deposition", "Thin film growth"),
                    ("magnetometer", "Magnetic Characterisation"),
                    ("furnace", "Furnace"),
                    ("transport", "Electrical Transport"),
                    ("characterisation", "Material Characterisation"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
