# Generated by Django 4.2.2 on 2023-06-18 22:04

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photologue", "0012_alter_photo_effect"),
        ("equipment", "0003_remove_equipment_photos_equipment_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="photos",
            field=models.ManyToManyField(blank=True, related_name="equipment", to="photologue.photo"),
        ),
    ]
