# Generated by Django 4.2.2 on 2023-06-18 22:09

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_equipment_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="photos",
        ),
    ]
