# Generated by Django 4.2.17 on 2025-01-28 22:01

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_shift_weighting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deposition", "Thin film growth"),
                    ("characterisation", "Material Characterisation"),
                    ("magnetometer", "Magnetic Characterisation"),
                    ("cryostat", "Cryostat"),
                    ("transport", "Electrical Transport"),
                    ("furnace", "Furnace"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
