# Generated by Django 4.2.2 on 2023-06-24 17:21

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0007_equipment_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserListEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="equipment.equipment"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
