# Generated by Django 4.2.19 on 2025-02-20 16:20

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0007_costrate_costcentre_rate"),
        ("equipment", "0007_equipment_users_alter_userlistentry_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargingRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_rate",
                    models.FloatField(default=0.0, verbose_name="Cost per shift"),
                ),
                (
                    "cost_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_rates",
                        to="costings.costrate",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_rates",
                        to="equipment.equipment",
                    ),
                ),
            ],
        ),
    ]
