# Generated by Django 4.2.19 on 2025-02-20 16:28

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0007_costrate_costcentre_rate"),
        ("equipment", "0008_chargingrate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chargingrate",
            unique_together={("equipment", "cost_rate")},
        ),
    ]
