# Generated by Django 4.2.2 on 2023-06-24 17:46

# Django imports
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0008_userlistentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlistentry",
            options={"ordering": ["equipment", "-role", "user"]},
        ),
        migrations.AlterUniqueTogether(
            name="userlistentry",
            unique_together={("equipment", "user")},
        ),
    ]
