# Generated by Django 4.2.2 on 2023-06-24 20:06

# Django imports
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("django_simple_file_handler", "0008_auto_20210702_1604"),
        ("equipment", "0009_alter_userlistentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="files",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, related_name="equipment", to="django_simple_file_handler.publicdocument"
            ),
        ),
    ]
