# Generated by Django 4.2.19 on 2025-02-20 16:35

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0009_alter_chargingrate_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingrate",
            name="comment",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
