# Generated by Django 4.2.2 on 2023-06-25 21:40

# Django imports
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_bookingentry_slot"),
        ("equipment", "0010_equipment_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="policies",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, related_name="equipment", to="bookings.bookingpolicy"
            ),
        ),
    ]
