# Generated by Django 4.2.19 on 2025-02-21 17:43

# Django imports
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0007_costrate_costcentre_rate"),
        ("equipment", "0010_chargingrate_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chargingrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chargingrate",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, null=True, verbose_name="Applicable Dates"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chargingrate",
            unique_together={("equipment", "cost_rate", "dates")},
        ),
    ]
