# Generated by Django 4.1 on 2023-07-09 17:21

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0012_alter_userlistentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
