# Generated by Django 4.1 on 2023-07-09 17:23

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0013_location_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("code",), name="Unique Location Code"),
        ),
    ]
