# Generated by Django 4.1 on 2023-07-11 17:45

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0014_location_unique location code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("-code",)},
        ),
    ]
