# Generated by Django 4.2.3 on 2023-07-18 15:24

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0017_document_alter_equipment_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlistentry",
            old_name="admin_gold",
            new_name="admin_hold",
        ),
        migrations.AddField(
            model_name="userlistentry",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userlistentry",
            name="hold",
            field=models.BooleanField(default=True, verbose_name="User clearable hold"),
        ),
    ]
