# Generated by Django 4.2.3 on 2023-07-21 22:30

# Django imports
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("flatpages", "0001_initial"),
        ("equipment", "0019_documentsignoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="pages",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, related_name="equipment", to="flatpages.flatpage"
            ),
        ),
    ]
