# Generated by Django 4.2.17 on 2024-12-24 21:39

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0021_shift_shift_positive_duration_constraint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="category",
            new_name="category",
        ),
    ]
