# Generated by Django 4.2.17 on 2025-01-01 17:41

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0022_rename_catagory_document_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="level",
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
