# Generated by Django 4.2.17 on 2025-01-02 14:56

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0023_location_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Booking Shift",
                "verbose_name_plural": "Booking Shifts",
            },
        ),
        migrations.RemoveConstraint(
            model_name="shift",
            name="Positive Duration Constraint",
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lte", models.F("end_time"))),
                name="Positive Duration Constraint",
            ),
        ),
    ]
