# Generated by Django 4.2.19 on 2025-02-18 22:27

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# external imports
import labman_utils.models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0007_equipment_users_alter_userlistentry_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", labman_utils.models.ObfuscatedHTMLField()),
                ("short_name", models.CharField(max_length=20)),
                ("account_code", models.CharField(max_length=20)),
                ("code", models.CharField(blank=True, max_length=80)),
                (
                    "level",
                    models.IntegerField(blank=True, default=None, editable=False, null=True),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_centres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name="cost_centres",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "locations",
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True,
                        help_text=None,
                        related_name="cost_centres",
                        to="equipment.location",
                    ),
                ),
                (
                    "super_cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_cost_centres",
                        to="costings.costcentre",
                    ),
                ),
            ],
            options={
                "ordering": ("-code",),
            },
        ),
        migrations.AddConstraint(
            model_name="costcentre",
            constraint=models.UniqueConstraint(fields=("name",), name="Unique Cost-centre Name"),
        ),
        migrations.AddConstraint(
            model_name="costcentre",
            constraint=models.UniqueConstraint(fields=("code",), name="Unique cost-centre Code"),
        ),
    ]
