# Generated by Django 4.2.19 on 2025-02-19 15:31

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcentre",
            name="people",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="cost_centres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="costcentre",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_cost_centres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
