# Generated by Django 4.2.19 on 2025-02-19 15:34

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costings", "0002_costcentre_people_alter_costcentre_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcentre",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_cost_centres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
