# Generated by Django 4.2.19 on 2025-02-19 15:59

# Django imports
from django.conf import settings
from django.db import migrations

# external imports
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costings", "0003_alter_costcentre_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcentre",
            name="people",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
