# Generated by Django 4.2.19 on 2025-02-19 20:23

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0005_alter_costcentre_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcentre",
            name="people",
        ),
    ]
