# Generated by Django 4.2.19 on 2025-02-19 20:53

# Django imports
import django.db.models.deletion
from django.db import migrations, models

# external imports
import labman_utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0006_remove_costcentre_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", labman_utils.models.ObfuscatedHTMLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="costcentre",
            name="rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="costings.costrate",
            ),
        ),
    ]
