# Generated by Django 4.2.17 on 2025-01-04 22:50

# Python imports
import datetime

# Django imports
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# external imports
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", tinymce.models.HTMLField()),
                ("mondays", models.BooleanField(default=True)),
                ("tuesdays", models.BooleanField(default=True)),
                ("wednesdays", models.BooleanField(default=True)),
                ("thursdays", models.BooleanField(default=True)),
                ("fridays", models.BooleanField(default=True)),
                ("saturdays", models.BooleanField(default=True)),
                ("sundays", models.BooleanField(default=True)),
                ("start_time", models.TimeField(default=datetime.time(9, 0))),
                ("end_time", models.TimeField(default=datetime.time(18, 0))),
                (
                    "quantisation",
                    models.DurationField(default=datetime.timedelta(seconds=10800)),
                ),
                (
                    "immutable",
                    models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
                ),
                (
                    "max_forward",
                    models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True),
                ),
                (
                    "quota",
                    models.DurationField(blank=True, default=datetime.timedelta(days=2), null=True),
                ),
                ("use_shifts", models.BooleanField(default=True)),
                (
                    "booker_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booker_booking_policies",
                        to="accounts.role",
                    ),
                ),
                (
                    "for_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_policies",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Policy",
                "verbose_name_plural": "Booking Policies",
                "ordering": ["for_role"],
            },
        ),
        migrations.CreateModel(
            name="BookingEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "booker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proxy_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Slot",
                "verbose_name_plural": "Booking Slots",
                "ordering": ["equipment", "slot"],
            },
        ),
    ]
