# Generated by Django 4.2.2 on 2023-06-25 19:41

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_pages_alter_account_photos_and_more"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingentry",
            name="project",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to="accounts.project"),
        ),
    ]
