# Generated by Django 4.2.2 on 2023-06-25 21:37

# Python imports
import datetime

# Django imports
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models

# external imports
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_pages_alter_account_photos_and_more"),
        ("bookings", "0002_alter_bookingentry_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingentry",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="bookingentry",
            name="start_time",
        ),
        migrations.AddField(
            model_name="bookingentry",
            name="slot",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookingPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("description", tinymce.models.HTMLField()),
                ("mondays", models.BooleanField(default=True)),
                ("tuesdays", models.BooleanField(default=True)),
                ("wednesdays", models.BooleanField(default=True)),
                ("thursdays", models.BooleanField(default=True)),
                ("fridays", models.BooleanField(default=True)),
                ("saturdays", models.BooleanField(default=True)),
                ("sundays", models.BooleanField(default=True)),
                ("start_time", models.TimeField(default=datetime.time(9, 0))),
                ("end_time", models.TimeField(default=datetime.time(18, 0))),
                ("quantisation", models.DurationField(default=datetime.timedelta(seconds=10800))),
                ("immutable", models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ("max_forward", models.DurationField(blank=True, default=datetime.timedelta(days=2), null=True)),
                (
                    "for_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_policies",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
