# Generated by Django 4.2.2 on 2023-06-25 21:37

# Django imports
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_bookingentry_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingentry",
            name="slot",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
        ),
    ]
