# Generated by Django 4.2.17 on 2025-01-22 17:13

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_bookingpolicy_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingentry",
            name="shifts",
            field=models.FloatField(default=1.0),
        ),
    ]
