# Generated by Django 4.2.19 on 2025-02-18 22:32

# Django imports
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0001_initial"),
        ("bookings", "0004_bookingentry_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingentry",
            name="charge",
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingentry",
            name="cost_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_charges",
                to="costings.costcentre",
            ),
        ),
        migrations.AddField(
            model_name="bookingentry",
            name="ledger_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
