# Generated by Django 4.2.2 on 2023-06-25 22:33

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_pages_alter_account_photos_and_more"),
        ("bookings", "0004_alter_bookingentry_slot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingentry",
            options={
                "ordering": ["equipment", "slot"],
                "verbose_name": "Booking Slot",
                "verbose_name_plural": "Booking Slots",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingpolicy",
            options={
                "ordering": ["for_role"],
                "verbose_name": "Booking Policy",
                "verbose_name_plural": "Booking Policies",
            },
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="booker_role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booker_booking_policies",
                to="accounts.role",
            ),
        ),
    ]
