# Generated by Django 4.2.19 on 2025-02-19 16:27

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_bookingentry_charge_bookingentry_cost_centre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingentry",
            name="project",
        ),
    ]
