# Generated by Django 4.2.2 on 2023-06-25 22:43

# Python imports
import datetime

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_pages_alter_account_photos_and_more"),
        ("bookings", "0005_alter_bookingentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="quota",
            field=models.DurationField(blank=True, default=datetime.timedelta(days=2), null=True),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="booker_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="booker_booking_policies", to="accounts.role"
            ),
        ),
    ]
