# Generated by Django 4.2.2 on 2023-06-25 22:44

# Python imports
import datetime

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_bookingpolicy_quota_alter_bookingpolicy_booker_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpolicy",
            name="max_forward",
            field=models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True),
        ),
    ]
