# Generated by Django 4.2.19 on 2025-02-21 16:10

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_bookingentry_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingentry",
            name="comment",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
