# Generated by Django 4.1 on 2023-07-11 17:45

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0007_alter_bookingpolicy_max_forward"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingentry",
            name="booker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proxy_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
