# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', tinymce.models.HTMLField(default=b'&nbsp;')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
