# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160328_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
