# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lm_utils.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_event_color_event'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('lm_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Calendar')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='contenttypes.ContentType')),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.CreateModel(
            name='BookingRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookable_days', lm_utils.models.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (7, 'Sunday')], max_length=13, null=True)),
                ('limit', models.TimeField(blank=True, null=True)),
                ('immutable', models.TimeField(blank=True, null=True)),
                ('can_book', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_edith_other', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='bookings.BookingPolicy')),
                ('user_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lm_utils.UserList_level')),
            ],
            options={
                'ordering': ['-user_level__leve'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookingpolicy',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
