# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrights',
            options={'ordering': ['-user_level__level']},
        ),
        migrations.AlterField(
            model_name='bookingrights',
            name='immutable',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrights',
            name='limit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
